spring:
  data: 
    mongodb: 
      address: 127.0.0.1:27017
      #,127.0.0.1:27017,127.0.0.1:27017
      #replica-set: rs0
      database: box
      username: boxhill
      password: 123456
      min-connections-per-host: 3
      max-connections-per-host: 20
      threads-allowed-to-block-for-connection-multiplier: 5
      server-selection-timeout: 30000
      max-wait-time: 120000
      max-connection-idel-time: 0
      max-connection-life-time: 0
      connect-timeout: 10000
      socket-timeout: 0
      socket-keep-alive: false
      ssl-enabled: false
      ssl-invalid-host-name-allowed: false
      always-use-m-beans: false
      heartbeat-socket-timeout: 20000
      heartbeat-connect-timeout: 20000
      min-heartbeat-frequency: 500
      heartbeat-frequency: 10000
      ocal-threshold: 15
      authentication-database: box
