spring:
  datasource:
    url: jdbc:mysql://39.100.143.70:6306/box?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: box@)!(
    type: com.alibaba.druid.pool.DruidDataSource