spring:
  redis: 
    database: 0
    host: 39.100.233.94
    port: 6379
    password: boxhill
    timeout: 3000
    lettuce: 
      pool: 
        max-active: 100
        max-idle: 20
        min-idle: 3
        max-wait: 3000