server:
  servlet: 
    context-path: /base
    session:
      timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    
    max-threads: 20
    max-connections: 100
spring:
  application:
    name: base
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/

async: 
  pool: 
    corePoolSize: 10
    maxPoolSize: 15
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: async-task-exec-  

